import Head from 'next/head'
import { Inter } from 'next/font/google'
import { HomePage } from '@/src/components/home/home-page'

const inter = Inter({ subsets: ['latin'] })

export default function Home({events_categories}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage data={events_categories}/>
    </>
  )
}

export async function getServerSideProps() {
  const data = await import("../data/data");
  const {events_categories} = data;
  return {  
    props: {
      events_categories
    }
  }
}